
# -*- coding: utf-8 -*-
"""
Created on Wed Sep 17 19:22:00 2025

@author: yayun.chen
"""


import os
import numpy as np
import pandas as pd
from pathlib import Path
from linearmodels import PanelOLS



#===========================#
#    Helper: HTML report    #
#===========================#

REPORT_CSS = """
<style>
body { font-family: Georgia, 'Times New Roman', Times, serif; color:#222; margin: 24px; }
h1, h2, h3 { font-weight: 600; }
h1 { font-size: 24px; margin-bottom: 8px; }
h2 { font-size: 18px; margin-top: 24px; margin-bottom: 8px; }
p  { line-height: 1.5; }
.table-wrap { margin: 12px 0 28px 0; }
table { border-collapse: collapse; width: 100%; font-size: 14px; }
th, td { border: 1px solid #ddd; padding: 8px; text-align: right; }
th { background: #f7f7f7; text-align: center; }
td.term { text-align: left; }
.badge { display:inline-block; background:#eef3ff; border:1px solid #cdd9ff; color:#003; border-radius: 6px; padding:2px 8px; margin-right:6px; font-size:12px; }
.small { color:#666; font-size: 12px; }
hr { border: 0; border-top: 1px solid #eee; margin: 24px 0; }
.code { font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, "Liberation Mono", monospace; background:#fafafa; border:1px solid #eee; padding:6px 8px; border-radius:6px; }
</style>
"""

def results_to_df(results: PanelOLS):
    """Build a tidy dataframe with coef, se, t, p, and 95% CI."""
    params = results.params.rename("coef")
    se = results.std_errors.rename("std_err")
    tstats = results.tstats.rename("t")
    pvals = results.pvalues.rename("pval")
    ci = results.conf_int()
    ci.columns = ["ci_lo", "ci_hi"]
    out = pd.concat([params, se, tstats, pvals, ci], axis=1)
    out.index.name = "term"
    return out.reset_index()

def render_html_block(title, meta_badges: dict, df: pd.DataFrame, notes: list):
    """Return HTML for a single model block (title + meta + table + notes)."""
    cols = ["term", "coef", "std_err", "t", "pval", "ci_lo", "ci_hi"]
    show_cols = [c for c in cols if c in df.columns]
    df_fmt = df.copy()
    for c in ["coef", "std_err", "t", "ci_lo", "ci_hi"]:
        if c in df_fmt.columns:
            df_fmt[c] = df_fmt[c].map(lambda x: f"{x:,.4f}")
    if "pval" in df_fmt.columns:
        df_fmt["pval"] = df_fmt["pval"].map(lambda x: f"{x:.3g}")
    df_fmt["term"] = df_fmt["term"].astype(str)

    meta_html = " ".join([f'<span class="badge">{k}: {v}</span>' for k, v in meta_badges.items()])
    table_html = df_fmt[show_cols].to_html(index=False, escape=False, classes="reg-table")
    notes_html = "<br>".join([f'<span class="small">* {n}</span>' for n in notes])

    block = f"""
    <h2>{title}</h2>
    <div>{meta_html}</div>
    <div class="table-wrap">{table_html}</div>
    <div>{notes_html}</div>
    <hr>
    """
    return block

def write_html_report(crop_name, blocks_html, out_dir):
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    html = f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Regression Report - {crop_name}</title>{REPORT_CSS}</head>
<body>
<h1>Regression Report - {crop_name}</h1>
<p class="small">Generated by ClimateCropYield pipeline.</p>
{blocks_html}
</body></html>
"""
    out_path = out_dir / f"regression_report_{crop_name}.html"
    out_path.write_text(html, encoding="utf-8")
    return str(out_path)


 
def build_prediction_table(res, preds, cyr, crop_name=None, irr_num=None, collapse_to_county=False):
    """
    Build a robust prediction table with:
      - crop_name, irr_num for traceability
      - fips, year
      - actual_YIELD (dedup across sub-crops, prefer CENSUS if mixed)
      - pred_noFE  := fitted_values (treated as climate-only baseline)
      - fixed_effect (entity FE; one α_i per fips)
      - pred_withFE := pred_noFE + fixed_effect
      - diff_pct := % difference (pred_withFE vs actual_YIELD)
      - AREA_HARVESTED, PRODUCTION
    """
    import numpy as np
    import pandas as pd

    print("\n===== build_prediction_table: START =====")

    # --- Step A: Training data
    train = cyr._train.reset_index()
    if irr_num is not None and "irr" not in train.columns:
        train["irr"] = irr_num
    print(f"[A] train shape: {train.shape}, cols[:10]: {list(train.columns)[:10]}")

    # --- Step B: Deduplication: one row per fips-year (prefer CENSUS if mixed)
    if "source_desc" in train.columns:
        def collapse(df):
            if "CENSUS" in df["source_desc"].values:
                df = df[df["source_desc"] == "CENSUS"]
            if df["YIELD"].notna().any():
                df = df[df["YIELD"].notna()]
            return pd.Series({
                "actual_YIELD": df["YIELD"].mean(skipna=True),
                "AREA_HARVESTED": df["AREA_HARVESTED"].sum(skipna=True) if "AREA_HARVESTED" in df else np.nan,
                "PRODUCTION": df["PRODUCTION"].sum(skipna=True) if "PRODUCTION" in df else np.nan,
            })
        group_cols = [c for c in ["fips","year","irr"] if c in train.columns]
        train_dedup = train.groupby(group_cols, as_index=False).apply(collapse)
    else:
        group_cols = [c for c in ["fips","year","irr"] if c in train.columns]
        train_dedup = (train
            .groupby(group_cols, as_index=False)
            .agg({
                "YIELD": "mean",
                "AREA_HARVESTED": "sum" if "AREA_HARVESTED" in train else "size",
                "PRODUCTION": "sum" if "PRODUCTION" in train else "size",
            })
            .rename(columns={"YIELD":"actual_YIELD"})
        )

    train_dedup["fips"] = train_dedup["fips"].astype(str)
    train_dedup["year"] = train_dedup["year"].astype(int)
    if "irr" in train_dedup: train_dedup["irr"] = train_dedup["irr"].astype(int)

    print(f"[B] train_dedup rows: {len(train_dedup)}")

    # --- Step C: Prediction skeleton (all years, no filtering)
    if preds is not None and not preds.empty:
        key_cols = [c for c in ["fips","year","irr"] if c in preds.columns]
        pred_keys = preds[key_cols].drop_duplicates().copy()
        pred_keys["fips"] = pred_keys["fips"].astype(str)
        pred_keys["year"] = pred_keys["year"].astype(int)
        if "irr" not in pred_keys and irr_num is not None:
            pred_keys["irr"] = irr_num
        preds_tbl = pred_keys.merge(train_dedup, on=[c for c in ["fips","year","irr"] if c in pred_keys], how="left")
        print(f"[C] using preds keys, merged shape: {preds_tbl.shape}")
    else:
        preds_tbl = train_dedup.copy()
        print(f"[C] fallback preds_tbl built, years={sorted(preds_tbl['year'].unique())}")

    # --- Step D: Baseline predictions (fitted_values -> pred_noFE)
    try:
        ef = res.estimated_effects
        if isinstance(ef, pd.Series):
            fe_df = ef.to_frame("fixed_effect").reset_index()
        else:
            col = ef.columns[0] if hasattr(ef, "columns") else "fixed_effect"
            fe_df = ef.reset_index().rename(columns={col: "fixed_effect"})

        if "entity" in fe_df.columns and "fips" not in fe_df.columns:
            fe_df = fe_df.rename(columns={"entity": "fips"})
        if "time" in fe_df.columns and "year" not in fe_df.columns:
            fe_df = fe_df.rename(columns={"time": "year"})

        fe_df["fips"] = fe_df["fips"].astype(str)
        fe_df["year"] = fe_df["year"].astype(int)

        preds_tbl = preds_tbl.merge(fe_df[["fips","year","fixed_effect"]], on=["fips","year"], how="left")

        print(f"[D] FE merge done -> preds_tbl shape={preds_tbl.shape}")
        print(preds_tbl[["fips","year","fixed_effect"]].head(5))
    except Exception as e:
        print(f"[WARN] [D] FE merge failed: {e}")
        preds_tbl["fixed_effect"] = np.nan

    # ---------- Step E: Pull fitted_withFE from model & merge ----------
    try:
        fitted = res.fitted_values
        if isinstance(fitted, pd.Series):
            fv = fitted.to_frame("fitted_withFE").reset_index()
        else:
            c0 = fitted.columns[0] if hasattr(fitted, "columns") else "fitted_withFE"
            fv = fitted.reset_index().rename(columns={c0: "fitted_withFE"})

        # normalize keys
        if "entity" in fv.columns and "fips" not in fv.columns:
            fv = fv.rename(columns={"entity":"fips"})
        if "time" in fv.columns and "year" not in fv.columns:
            fv = fv.rename(columns={"time":"year"})
        fv["fips"] = fv["fips"].astype(str)
        fv["year"] = fv["year"].astype(int)

        before_cols = set(preds_tbl.columns)
        preds_tbl = preds_tbl.merge(fv[["fips","year","fitted_withFE"]], on=["fips","year"], how="left")
        after_new_cols = set(preds_tbl.columns) - before_cols

        print(f"\n[E] fitted_withFE rows={len(fv)} | merged preds_tbl shape={preds_tbl.shape}")
        print("[E] new columns from fitted merge:", after_new_cols)
        print("[E] fitted_withFE coverage:", preds_tbl["fitted_withFE"].notna().mean())
        print("[E] sample fitted rows:\n", preds_tbl[["fips","year","fitted_withFE"]].head(6))
    except Exception as e:
        print(f"[WARN] [E] fitted_withFE merge failed: {e}")
        preds_tbl["fitted_withFE"] = np.nan
        
    
# ---------- Step F: Build pred_noFE & pred_withFE ----------
    preds_tbl["pred_noFE"] =preds_tbl["fitted_withFE"].fillna(0.0)
    preds_tbl["pred_withFE"] =  preds_tbl["fixed_effect"] + preds_tbl["pred_noFE"]


    print("\n[F] Constructed pred_noFE and pred_withFE.")
    print("[F] coverage pred_withFE:", preds_tbl["pred_withFE"].notna().mean())
    print("[F] coverage pred_noFE:", preds_tbl["pred_noFE"].notna().mean())
    with np.errstate(all='ignore'):
        print("[F] pred_noFE describe:\n", preds_tbl["pred_noFE"].describe())
        print("[F] pred_withFE describe:\n", preds_tbl["pred_withFE"].describe())

    sample_cols = [c for c in ["fips","year","actual_YIELD","fixed_effect","fitted_withFE","pred_noFE","pred_withFE"] if c in preds_tbl.columns]
    print("[F] sample rows:\n", preds_tbl[sample_cols].head(8))

    # ---------- Step G: % difference vs actual ----------
    preds_tbl["diff_pct"] = np.where(
        preds_tbl["actual_YIELD"].notna() & (preds_tbl["actual_YIELD"] != 0),
        100.0 * (preds_tbl["pred_withFE"] - preds_tbl["actual_YIELD"]) / preds_tbl["actual_YIELD"],
        np.nan
    )
    print("\n[G] diff_pct coverage:", preds_tbl["diff_pct"].notna().mean())
    print("[G] diff_pct describe (dropna):\n", preds_tbl["diff_pct"].dropna().describe())

    # ---------- Step H: Latest-year-per-county summary ----------
    if "year" in preds_tbl.columns and preds_tbl["year"].notna().any():
        latest_mask = preds_tbl.groupby("fips")["year"].transform("max") == preds_tbl["year"]
        latest_tbl = preds_tbl[latest_mask].copy()
        avg_diff_pct = latest_tbl["diff_pct"].mean(skipna=True)
        print(f"\n[H] Latest-year rows: {len(latest_tbl)} / {len(preds_tbl)}")
        print(f"[H] Average % diff (latest year per county): {avg_diff_pct:.2f}%")
    else:
        print("\n[WARN] [H] 'year' missing; skipping latest-year summary.")

    # ---------- Step I: metadata, dedup, (optional) collapse ----------
    if crop_name is not None: preds_tbl["crop_name"] = crop_name
    if irr_num is not None:   preds_tbl["irr_num"] = irr_num

    dedup_keys = [c for c in ["fips","year","irr_num"] if c in preds_tbl.columns]
    if dedup_keys:
        before = len(preds_tbl)
        preds_tbl = preds_tbl.drop_duplicates(subset=dedup_keys)
        print(f"\n[I] Dedup on {dedup_keys}: {before} -> {len(preds_tbl)}")

    if collapse_to_county:
        group_cols = ["fips"] + (["irr_num"] if "irr_num" in preds_tbl.columns else [])
        preds_tbl = preds_tbl.groupby(group_cols, as_index=False).agg({
            "actual_YIELD":"mean",
            "pred_noFE":"mean",
            "fixed_effect":"mean",
            "pred_withFE":"mean",
            "diff_pct":"mean",
            "AREA_HARVESTED":"sum" if "AREA_HARVESTED" in preds_tbl.columns else "size",
            "PRODUCTION":"sum" if "PRODUCTION" in preds_tbl.columns else "size",
        })
        print(f"[I] Collapsed to county level: shape={preds_tbl.shape}")

    # ---------- Step J: final sanity ----------
    with np.errstate(all='ignore'):
        if "actual_YIELD" in preds_tbl:
            print("\n[J] actual_YIELD describe:\n", preds_tbl["actual_YIELD"].describe())
        if "pred_withFE" in preds_tbl:
            print("[J] pred_withFE describe:\n", preds_tbl["pred_withFE"].describe())
        if "pred_noFE" in preds_tbl:
            print("[J] pred_noFE describe:\n", preds_tbl["pred_noFE"].describe())
        if "fixed_effect" in preds_tbl:
            print("[J] fixed_effect describe:\n", preds_tbl["fixed_effect"].describe())

#    print(preds_tbl)
    return preds_tbl

def export_models_html_no_bootstrap(crop_name, raw_data, models, out_dir):
    """
    Export the selected model(s) to HTML with coefficients, regression summary,
    and prediction tables. Normally called with the single lowest-MSE in-range
    spec, but it will render any number of rows. Prediction tables:
      - Show all years internally
      - Filter for 2022 if available, else latest year
      - Display actual vs predicted (with FE) and % difference
      - Add average % diff summary
    """
    import os, re, html
    import pandas as pd
    import numpy as np

    # imported here, not at module scope: Climate_model imports this module,
    # so a top-level import would be circular.
    from src.Climate_model import ClimateCropYield

    os.makedirs(out_dir, exist_ok=True)

    def _safe_name(s: str) -> str:
        return re.sub(r'[^A-Za-z0-9._-]+', '_', str(s)).strip('_')

    blocks = []

    for i, r in enumerate(models.itertuples(index=False), start=1):
        print("\n===============================")
        print(f"> Exporting model rank {i}, ID={r.model_id}")
        print("===============================")

        irr_num = 1 if r.irrig == "irrig" else 2
        cyr = ClimateCropYield(crop_name, irr_num, raw_data)
        cyr.DataProcess()

        res, preds, testreg, X = cyr.QuickModel(
            highhere=int(r.high),
            lowhere=int(r.low),
            timetrend=r.timetrend,
            return_test=True
        )
        if res is None:
            print("[FAIL] Skipping model - no results.")
            continue

        # === Get full prediction table
        preds_tbl = build_prediction_table(res, preds, cyr, crop_name, irr_num)

        # add %diff between actual and pred_withFE
        if "actual_YIELD" in preds_tbl and "pred_withFE" in preds_tbl:
            preds_tbl["pct_diff"] = (
                100 * (preds_tbl["pred_withFE"] - preds_tbl["actual_YIELD"])
                / preds_tbl["actual_YIELD"].replace(0, np.nan)
            )

        # === Filter to 2022 or latest year
        if (preds_tbl["year"] == 2022).any():
            preds_show = preds_tbl[preds_tbl["year"] == 2022].copy()
            year_used = 2022
        else:
            year_used = int(preds_tbl["year"].max())
            preds_show = preds_tbl[preds_tbl["year"] == year_used].copy()

        # select only required columns
        show_cols = [
            "fips","year","irr",
            "actual_YIELD","AREA_HARVESTED","PRODUCTION",
            "fixed_effect","pred_withFE","pct_diff"
        ]
        show_cols = [c for c in show_cols if c in preds_show.columns]
        preds_show = preds_show[show_cols].copy()
        if "pct_diff" in preds_show:
            preds_show["pct_diff"] = preds_show["pct_diff"].round(2)

        # summary average difference
        avg_diff = preds_show["pct_diff"].mean(skipna=True)

        # === Save to CSV (all years, full table)
        csv_file = f"{_safe_name(crop_name)}_model{i}_{_safe_name(r.model_id)}_preds.csv"
        csv_path = os.path.join(out_dir, csv_file)
        preds_tbl.to_csv(csv_path, index=False)
        print(f"[SAVE] Saved full predictions table to: {csv_path}")

        # --- Coefficient table
        try:
            ci = res.conf_int(); ci.columns = ["ci_lo", "ci_hi"]
            coef_tbl = pd.concat(
                [res.params.rename("coef"),
                 res.std_errors.rename("std_err"),
                 res.tstats.rename("t"),
                 res.pvalues.rename("pval"),
                 ci],
                axis=1
            ).reset_index()
            if "index" in coef_tbl.columns:
                coef_tbl = coef_tbl.rename(columns={"index":"term"})
        except Exception as e:
            coef_tbl = pd.DataFrame()
            print("[WARN] Could not build coefficient table:", e)

        # --- Regression summary
        try:
            reg_summary = str(res.summary)
        except Exception as e:
            reg_summary = f"[WARN] Could not capture regression summary: {e}"

        # --- Build HTML block
        block_html = []
        block_html.append(f"<h2>Model #{i} (model_id={html.escape(str(r.model_id))})</h2>")
        block_html.append(
            f"<p><b>Picked thresholds:</b> Low={r.low} °C, High={r.high} °C, Trend={r.timetrend}</p>"
        )
        block_html.append("<h3>Coefficient Table</h3>")
        block_html.append(coef_tbl.to_html(index=False))
        block_html.append("<h3>Regression Summary</h3>")
        block_html.append(f"<pre>{html.escape(reg_summary)}</pre>")
        block_html.append(f"<h3>Predictions (year {year_used})</h3>")
        block_html.append(preds_show.to_html(index=False))
        block_html.append(f"<p><b>Average % difference:</b> {avg_diff:.2f}%</p>")
        blocks.append("\n".join(block_html))

    # --- Final HTML
    page_title = f"Selected Model - {crop_name}"
    html_doc = f"""<!doctype html>
<html lang="en">
<head><meta charset="utf-8"><title>{page_title}</title></head>
<body>
<h1>{page_title}</h1>
{"<hr/>".join(blocks)}
</body>
</html>"""

    out_path = os.path.join(out_dir, f"{_safe_name(crop_name)}_best_model_report.html")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(html_doc)
    print(f"\n[OK] Export complete. HTML written to: {out_path}")
    return out_path
